server:
  port: 8081

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_events
    username: ticketing
    password: ticketing
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

booking:
  service:
    base-url: http://localhost:8082

logging:
  level:
    com.ticketing: DEBUG
    org.hibernate.SQL: WARN
